spring:
  flyway:
    out-of-order: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/kino-cms-db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  data:
    web.pageable.one-indexed-parameters: true
  web:
    resources:
      static-locations: classpath:/static/html/

server:
  servlet:
    context-path: ""

movies.image-gallery:
  mapper:
    delimiter: "\\s"
    default-image: "default.jpg"

admin:
  username: "admin"
  password: "admin"